# Generated by Django 4.0 on 2021-12-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RK_app.computer')),
            ],
        ),
    ]
